### ISSUE TITLE
Sólo necesitas un getElementById. En el window.onload

### ISSUE THREAD

**Issue by lmagarin** [R4f4Lc/DWEC2Daw#3]
Sólo necesitas un getElementById. En el window.onload
https://github.com/R4f4Lc/DWEC2Daw/blob/7405d856fd74b9e7bef46be9adabaa52d92b80fa/Tema%202/Practica%202.5/js/ejercicio16.js#L24

**Comment by R4f4Lc** [comment]
Código JS proporcionado por el ejercicio y pedía utilizarlo.

**Comment by lmagarin** [comment]
Tienes razón, pero tenéis que optimizarlo con todo lo que hemos hablado
